# Generated by Django 5.0 on 2023-12-27 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_manager",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="is_moderator",
            field=models.BooleanField(default=False),
        ),
    ]
