# Generated by Django 5.0 on 2023-12-28 13:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="manufacturer",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
