# Generated by Django 5.0 on 2023-12-29 14:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0005_category_product_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["name"]},
        ),
    ]
