# Generated by Django 5.0 on 2023-12-29 14:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0006_alter_category_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["id"]},
        ),
    ]
