# Generated by Django 5.0 on 2024-01-12 10:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0010_product_folder_path"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="folder_path",
            new_name="image_path",
        ),
    ]
