# Generated by Django 5.0 on 2024-01-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0011_rename_folder_path_product_image_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="inventory",
            field=models.IntegerField(default=0),
        ),
    ]
