# Generated by Django 5.0 on 2024-01-15 13:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0012_product_inventory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="inventory",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
